version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DEBUG=True

volumes:
  media_data: